=== vladimir-chernykh/LRk/data/grammar.xsd
<?xml version="1.0" encoding="windows-1251"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  targetNamespace="http://en.wikipedia.org/wiki/Uniform_resource_identifier" 
  xmlns:t="http://en.wikipedia.org/wiki/Uniform_resource_identifier">
  
  <xs:element name="grammar" type="t:grammarType"/>
  
    <xs:complexType name="grammarType">
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="1" name="NS" type="xs:string" />
        <xs:element maxOccurs="unbounded" name="TS" type="xs:string" />
        <xs:element maxOccurs="unbounded" name="PR">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="left" maxOccurs="1" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="PRS">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="order" type="xs:unsignedByte" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="right" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs ="0" maxOccurs="unbounded" name="PRS">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="order" type="xs:unsignedByte" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="order" type="xs:unsignedByte" use="optional" />
          </xs:complexType>
        </xs:element>
        <xs:element name="SS" maxOccurs="1" minOccurs="1" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  
</xs:schema>

=== vladimir-chernykh/LRk/data/grammar4.xml
<?xml version="1.0" encoding="Windows-1251"?>
<?xml-stylesheet type='text/xsl' href="grammar.xsl"?>
<grammar xmlns="http://umeta.ru/namespaces/trpl"  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://umeta.ru/namespaces/trpl grammar.xsd'>
  <NS>S</NS>
  <NS>[q0aq0]</NS>
  <NS>[q0aq1]</NS>
  <NS>[q1aq0]</NS>
  <NS>[q1aq1]</NS>
  <NS>[q0Z0q0]</NS>
  <NS>[q0Z0q1]</NS>
  <NS>[q1Z0q0]</NS>
  <NS>[q1Z0q1]</NS>
  <TS>a</TS>
  <TS>b</TS>
  <PR>
    <left>
      <PRS order="1">S</PRS>
    </left>
    <right>
      <PRS order="1">a</PRS>
      <PRS order="2">[q0aq0]</PRS>
      <PRS order="3">[q0Z0q0]</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">S</PRS>
    </left>
    <right>
      <PRS order="1">a</PRS>
      <PRS order="2">[q0aq1]</PRS>
      <PRS order="3">[q1Z0q0]</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">S</PRS>
    </left>
    <right>
      <PRS order="1">a</PRS>
      <PRS order="2">[q0aq0]</PRS>
      <PRS order="3">[q0Z0q1]</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">S</PRS>
    </left>
    <right>
      <PRS order="1">a</PRS>
      <PRS order="2">[q0aq1]</PRS>
      <PRS order="3">[q1Z0q1]</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">S</PRS>
    </left>
    <right>
      <PRS order="1">a</PRS>
      <PRS order="2">[q0aq1]</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">[q0Z0q0]</PRS>
    </left>
    <right>
      <PRS order="1">a</PRS>
      <PRS order="2">[q0aq0]</PRS>
      <PRS order="3">[q0Z0q0]</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">[q0Z0q0]</PRS>
    </left>
    <right>
      <PRS order="1">a</PRS>
      <PRS order="2">[q0aq1]</PRS>
      <PRS order="3">[q1Z0q0]</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">[q0Z0q1]</PRS>
    </left>
    <right>
      <PRS order="1">a</PRS>
      <PRS order="2">[q0aq0]</PRS>
      <PRS order="3">[q0Z0q1]</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">[q0Z0q1]</PRS>
    </left>
    <right>
      <PRS order="1">a</PRS>
      <PRS order="2">[q0aq1]</PRS>
      <PRS order="3">[q1Z0q1]</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">[q0Z0q1]</PRS>
    </left>
    <right>
      <PRS order="1">a</PRS>
      <PRS order="2">[q0aq1]</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">[q0aq0]</PRS>
    </left>
    <right>
      <PRS order="1">a</PRS>
      <PRS order="2">[q0aq0]</PRS>
      <PRS order="3">[q0aq0]</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">[q0aq0]</PRS>
    </left>
    <right>
      <PRS order="1">a</PRS>
      <PRS order="2">[q0aq1]</PRS>
      <PRS order="3">[q1aq0]</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">[q0aq1]</PRS>
    </left>
    <right>
      <PRS order="1">a</PRS>
      <PRS order="2">[q0aq0]</PRS>
      <PRS order="3">[q0aq1]</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">[q0aq1]</PRS>
    </left>
    <right>
      <PRS order="1">a</PRS>
      <PRS order="2">[q0aq1]</PRS>
      <PRS order="3">[q1aq1]</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">[q0aq1]</PRS>
    </left>
    <right>
      <PRS order="1">b</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">[q1aq1]</PRS>
    </left>
    <right>
      <PRS order="1">b</PRS>
    </right>
  </PR>
  <SS>S</SS>
</grammar>

=== vladimir-chernykh/LRk/data/grammar2.xml
<?xml version="1.0" encoding="Windows-1251"?>
<?xml-stylesheet type='text/xsl' href='grammar.xsl'?>
<grammar xmlns="http://umeta.ru/namespaces/trpl"  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://umeta.ru/namespaces/trpl grammar.xsd'>
  <NS>E</NS>
  <NS>T</NS>
  <NS>F</NS>
  <NS>E'</NS>
  <NS>T'</NS>
  <TS>*</TS>
  <TS>+</TS>
  <TS>id</TS>
  <PR>
    <left>
      <PRS order="1">E</PRS>
    </left>
    <right>
      <PRS order="1">T</PRS>
      <PRS order="2">E'</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">E'</PRS>
    </left>
    <right>
      <PRS order="1">+</PRS>
      <PRS order="2">T</PRS>
      <PRS order="3">E'</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">E'</PRS>
    </left>
    <right/>
  </PR>
  <PR>
    <left>
      <PRS order="1">T</PRS>
    </left>
    <right>
      <PRS order="1">F</PRS>
      <PRS order="2">T'</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">T'</PRS>
    </left>
    <right>
      <PRS order="1">*</PRS>
      <PRS order="2">F</PRS>
      <PRS order="3">T'</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">T'</PRS>
    </left>
    <right/>
  </PR>
  <PR>
    <left>
      <PRS order="1">F</PRS>
    </left>
    <right>
      <PRS order="1">id</PRS>
    </right>
  </PR>
  <SS>E</SS>
</grammar>

=== vladimir-chernykh/LRk/data/grammar3.xml
<?xml version="1.0" encoding="Windows-1251"?>
<?xml-stylesheet type='text/xsl' href="grammar.xsl"?>
<grammar xmlns="http://umeta.ru/namespaces/trpl"  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://umeta.ru/namespaces/trpl grammar.xsd'>
  <NS>S</NS>
  <NS>A</NS>
  <NS>B</NS>
  <TS>a</TS>
  <TS>b</TS>
  <PR>
    <left>
      <PRS order="1">S</PRS>
    </left>
    <right>
      <PRS order="1">A</PRS>
      <PRS order="2">a</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">S</PRS>
    </left>
    <right>
      <PRS order="1">B</PRS>
      <PRS order="2">a</PRS>
      <PRS order="3">b</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">A</PRS>
    </left>
    <right>
      <PRS order="1">a</PRS>
    </right>
  </PR>
  <PR>
    <left>
      <PRS order="1">B</PRS>
    </left>
    <right>
      <PRS order="1">a</PRS>
    </right>
  </PR>
  <SS>S</SS>
</grammar>
